name: Android Build

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'   # lebih disarankan dibanding adopt

      # Pastikan gradlew bisa dieksekusi
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # Build project (bisa diganti assembleDebug kalau cuma butuh APK debug)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Upload artifact APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: task-flutter.apk
          path: app/build/outputs/apk/debug/app-debug.apk
